version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:    
    build:
      #Only the name of the file, not the path 
      dockerfile: Dockerfile.dev
      #Here we can specify the path
      context: ./server
    volumes:
      #Don't try to override the /app/node_modules
      - /app/node_modules
      #For anything else reffer to this path
      - ./server:/app
    environment:
      #Refers to the service, not a hardcoded IP
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      #Refers to the service, not a hardcoded IP
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'




